sudo: required
services:
  - docker

before_install:
  - docker build -t tandrosdiv/baby-api -f ./server/Dockerfile.dev ./server
  - docker build -t tandrosdiv/baby-crawler -f ./crawler/Dockerfile.dev ./crawler

script:
  # regression test
  - docker run -e CI=true tandrosdiv/baby-api npm run test
  - docker run -e CI=true tandrosdiv/baby-crawler npm run test:prod
  # - docker run -e CI=true tandrosdiv/baby-crawler /app/node_modules/.bin/snyk auth "$SNYK_TOKEN" 
  - docker run -e CI=true tandrosdiv/baby-crawler /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:test"
  - >
    docker run -e CI=true -v "$PWD/coverage:/app/coverage" tandrosdiv/baby-crawler 
    /bin/bash -c "npm run test:codecov"
  - bash <(curl -s https://codecov.io/env)
  - bash <(curl -s https://codecov.io/bash) 

after_success:
  - docker run -e CI=true tandrosdiv/baby-crawler /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:monitor"
  - docker build -t tandrosdiv/baby-api ./server
  - docker build -t tandrosdiv/baby-crawler ./crawler
  # add snyk monitoring
  # Log in to Docker CLI, TC
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker Hub
  - docker push tandrosdiv/baby-api
  - docker push tandrosdiv/baby-crawler