sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in baby-domains-249012-53cfe28387fb.json.enc -out baby-domains-249012-53cfe28387fb.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file baby-domains-249012-53cfe28387fb.json
  - gcloud config set project baby-domains-249012 
  - gcloud config set compute/zone europe-west3-c
  - gcloud container clusters get-credentials baby-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t tandrosdiv/baby-api -f ./server/Dockerfile.dev ./server
  - docker build -t tandrosdiv/baby-crawler -f ./crawler/Dockerfile.dev ./crawler

script:
  # regression test
  - docker run -e CI=true tandrosdiv/baby-api npm run test
  - docker run -e CI=true tandrosdiv/baby-crawler npm run test:prod
  # - docker run -e CI=true tandrosdiv/baby-crawler /app/node_modules/.bin/snyk auth "$SNYK_TOKEN" 
  - docker run -e CI=true tandrosdiv/baby-crawler /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:test"
  - docker run -e CI=true tandrosdiv/baby-api /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:test"

  - >
    docker run -e CI=true -v "$PWD/coverage:/app/coverage" tandrosdiv/baby-crawler 
    /bin/bash -c "npm run test:codecov"
  - bash <(curl -s https://codecov.io/env)
  - bash <(curl -s https://codecov.io/bash) 

after_success:
  - docker run -e CI=true tandrosdiv/baby-crawler /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:monitor"
  - docker run -e CI=true tandrosdiv/baby-api /bin/bash -c "snyk auth $SNYK_TOKEN && npm run snyk:monitor"
 
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master