sudo: required
services:
  - docker

before_install:
  - docker build -t tandrosdiv/baby-api -f ./server/Dockerfile.dev ./server

script:
  # regression test
  - docker run -e CI=true tandrosdiv/baby-api npm run test

after_success:
  - docker build -t tandrosdiv/baby-api ./server
  # Log in to Docker CLI, TC
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker Hub
  docker push tandrosdiv/baby-div