apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: tandrosdiv/baby-crawler
      context: crawler
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/crawler-deployment.yaml