FROM node:latest

WORKDIR /app

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y mercurial

RUN npm install -g snyk
COPY package.json .
COPY .snyk .
RUN npm install
RUN npm run snyk-protect

COPY . .

CMD ["npm", "run", "start:ci"]