apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-creator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-creator
  template:
    metadata:
      labels:
        component: api-creator
    spec:
      dnsPolicy: Default
      containers:
        - name: api-creator
          image: tandrosdiv/baby-api-creator
          env: 
            - name: MONGOPROTOCOL
              valueFrom: 
                secretKeyRef:
                  name: mongoprotocol
                  key: MONGOPROTOCOL
            - name: MONGOUSER
              valueFrom: 
                secretKeyRef:
                  name: mongouser
                  key: MONGOUSER
            - name: MONGOHOST
              valueFrom: 
                secretKeyRef:
                  name: mongohost
                  key: MONGOHOST
            - name: MONGODATABASE
              valueFrom: 
                secretKeyRef:
                  name: mongodatabase
                  key: MONGODATABASE
            - name: MONGOPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongopassword
                  key: MONGOPASSWORD
            - name: MONGOPORT
              valueFrom: 
                secretKeyRef:
                  name: mongoport
                  key: MONGOPORT
            - name: NODE_ENV
              valueFrom: 
                secretKeyRef:
                  name: nodenv
                  key: NODE_ENV
            - name: CLOUDAMQP_URL
              valueFrom: 
                secretKeyRef:
                  name: cloudamqp-url
                  key: CLOUDAMQP_URL
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "200m"

