# apiVersion: v1
# kind: Service
# metadata:
#   name: api-creator-cluster-ip-service
#   labels:
#     component: api-creator
# spec:
#   clusterIP: None
#   selector:
#     component: api-creator
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-creator
spec:
  serviceName: api-creator
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: api-creator
  template:
    metadata:
      labels:
        component: api-creator
    spec:
      dnsPolicy: Default
      # volume
      volumes:
        - name: cb-pv
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name: api-creator
          image: tandrosdiv/baby-api-creator
          volumeMounts:
            - name: cb-pv
              mountPath: "/app/public"
          env: 
            - name: MONGOPROTOCOL
              valueFrom: 
                secretKeyRef:
                  name: mongoprotocol
                  key: MONGOPROTOCOL
            - name: MONGOUSER
              valueFrom: 
                secretKeyRef:
                  name: mongouser
                  key: MONGOUSER
            - name: MONGOHOST
              valueFrom: 
                secretKeyRef:
                  name: mongohost
                  key: MONGOHOST
            - name: MONGODATABASE
              valueFrom: 
                secretKeyRef:
                  name: mongodatabase
                  key: MONGODATABASE
            - name: MONGOPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongopassword
                  key: MONGOPASSWORD
            - name: MONGOPORT
              valueFrom: 
                secretKeyRef:
                  name: mongoport
                  key: MONGOPORT
            - name: NODE_ENV
              valueFrom: 
                secretKeyRef:
                  name: nodenv
                  key: NODE_ENV
            - name: CLOUDAMQP_URL
              valueFrom: 
                secretKeyRef:
                  name: cloudamqp-url
                  key: CLOUDAMQP_URL
            - name: RETENTION_POLICY
              valueFrom: 
                secretKeyRef:
                  name: retentionpolicy
                  key: RETENTION_POLICY
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
      initContainers:
        - name: fix-permissions-for-nfs-share
          image: busybox:1.31
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'chown -R 1000:1000 /app/public']
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: cb-pv
              mountPath: "/app/public"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

