apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbapi-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-ip-service.default.svc.cluster.local 
    path: "/"

---
kind: PersistentVolumeClaim
metadata:
  name: cbapi-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi