apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  labels:
    component: server
spec:
  clusterIP: None
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000