apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
  labels:
    component: webserver
spec:
  serviceName: webserver
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: webserver
  template:
    metadata:
      labels:
        component: webserver
    spec:
      dnsPolicy: Default
      volumes:
        - name: cb-pv
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name : webserver
          image: tandrosdiv/baby-api
          volumeMounts:
            - name: cb-pv
              mountPath: "/app/public"
          ports:
            - containerPort: 5000
          env:
            - name: MONGOPROTOCOL
              valueFrom: 
                secretKeyRef:
                  name: mongoprotocol
                  key: MONGOPROTOCOL
            - name: MONGOUSER
              valueFrom: 
                secretKeyRef:
                  name: mongouser
                  key: MONGOUSER
            - name: MONGOHOST
              valueFrom: 
                secretKeyRef:
                  name: mongohost
                  key: MONGOHOST
            - name: MONGODATABASE
              valueFrom: 
                secretKeyRef:
                  name: mongodatabase
                  key: MONGODATABASE
            - name: MONGOPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongopassword
                  key: MONGOPASSWORD
            - name: MONGOPORT
              valueFrom: 
                secretKeyRef:
                  name: mongoport
                  key: MONGOPORT
            - name: NODE_ENV
              valueFrom: 
                secretKeyRef:
                  name: nodenv
                  key: NODE_ENV
            - name: PORT
              valueFrom: 
                secretKeyRef:
                  name: expressport
                  key: PORT
          resources:
            limits:
              memory: "96Mi"
              cpu: "150m"   
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: fix-permissions-for-nfs-share
          image: busybox:1.31
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'chown -R 1000:1000 /app/public']
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: cb-pvinit
              mountPath: "/app/public"