FROM node:lts-buster-slim

WORKDIR /app

RUN apt-get install bash
RUN apt-get install git
RUN apt-get install curl
RUN apt-get install hg

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]