FROM node:latest

WORKDIR /app

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y mercurial

COPY package.json .
RUN npm install
RUN npm install -g snyk
RUN rm package-lock.json
COPY package-lock.json .

COPY . .

CMD ["npm", "run", "start:ci"]